In [303]:
data = {
    'height':[1.4, 1.2, 1.0, 1.5, 1.8],
    'fav_movie': ['baby-days-out','the original','pirates of the carribean','tom and jerry','wednesday'],
    'description':['this movie is somehow' for i in range(1,6)]
}

In [304]:
type(data)

dict

In [305]:
import pandas as pd
df = pd.DataFrame(data)

In [306]:
df

   height                 fav_movie            description
0     1.4             baby-days-out  this movie is somehow
1     1.2              the original  this movie is somehow
2     1.0  pirates of the carribean  this movie is somehow
3     1.5             tom and jerry  this movie is somehow
4     1.8                 wednesday  this movie is somehow

## Label Encoding

In [307]:
from sklearn.preprocessing import LabelEncoder  

# 2. Initialize the LabelEncoder
le = LabelEncoder()  # best used with hierarchy or ordinal data /#/ shouldnt be used on data that has order

# 3. Fit to the column and transform text to integers
df['encoded_class_movie']=le.fit_transform(df['fav_movie'])

print(df)

   height                 fav_movie            description  \
0     1.4             baby-days-out  this movie is somehow
1     1.2              the original  this movie is somehow
2     1.0  pirates of the carribean  this movie is somehow
3     1.5             tom and jerry  this movie is somehow
4     1.8                 wednesday  this movie is somehow

   encoded_class_movie
0                    0
1                    2
2                    1
3                    3
4                    4

## One Hot Encoding

In [308]:

# 2. Apply one-hot encoding and fix the dummy variable trap
# 'drop_first=True' removes the very first category column (alphabetically)
# 'dtype=int' changes the output from True/False booleans to 1/0 integers


df_encoded = pd.get_dummies(df, columns=['fav_movie'], dtype=int, drop_first=True)
# Print the resulting dataframe

In [309]:
df_encoded

,height,description,encoded_class_movie,fav_movie_pirates of the carribean,fav_movie_the original,fav_movie_tom and jerry,fav_movie_wednesday
0,1.4,this movie is somehow,0,0,0,0,0
1,1.2,this movie is somehow,2,0,1,0,0
2,1.0,this movie is somehow,1,1,0,0,0
3,1.5,this movie is somehow,3,0,0,1,0
4,1.8,this movie is somehow,4,0,0,0,1

## Bag Of Words

In [310]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# 1. Create a sample dataset with text reviews
data = {'reviews': ['the food is good',
                           'New food is terrible',
                           'good food and good services']
              }

df = pd.DataFrame(data)
df

# 2. Initialize the CountVectorizer
# stop_words='english' removes useless words like 'the' and 'and' to save memory
vectorizer = CountVectorizer(stop_words='english')

# 3. Fit and transform the text column 
# This learns the unique vocabulary and counts the word occurrences 
bow_matrix = vectorizer.fit_transform(df['reviews'])

# 4. Convert the matrix into a clean Pandas DataFrame
# vectorizer.get_feature_names_out() extracts the learned vocabulary as column names 

df_bow = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())

In [311]:
df_bow

   food  good  new  services  terrible
0     1     1    0         0         0
1     1     0    1         0         1
2     1     2    0         1         0

TF-IDF

## Word Embeddings

### Tokenization

In [312]:
#white space tokenization or white space splitting
text = 'Deep learning is amazing!'
tokens = text.split()

print(tokens)

['Deep', 'learning', 'is', 'amazing!']

In [313]:
text = 'Deep learning is amazing!'
tokens = text.split('e')

print(tokens)

['D', '', 'p l', 'arning is amazing!']

In [314]:
#regex tokenization
import re 
text = 'Deep learning is amazing!'
tokens = re.findall(r'\w+|[^\w\s]', text)

print(tokens)

['Deep', 'learning', 'is', 'amazing', '!']

In [315]:
# character level tokenization
text = 'Deep learning is amazing!'
tokens = list(text)

print(tokens)

['D', 'e', 'e', 'p', ' ', 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', ' ', 'i', 's', ' ', 'a', 'm', 'a', 'z', 'i', 'n', 'g', '!']

### Step By Step implementation of a simple Tokenizers

In [316]:
#opening the raw text file
with open('tokenizer.txt', 'r', encoding='utf-8') as f:
    raw_text = f.read()
len(raw_text),raw_text

(246,
 'captain@ jack sparrow ?is the greatest! of all pirates?\ngit status checks to see if the git project is tracked\n\ngit init% initializes an empty# git repository\nseed is the comp!any in which i am doing my internship$\nconsistency beats? motivation ?')

In [317]:
#whitespace splitting
import re
white_space_splitting = re.split(r'\s', raw_text)
print(white_space_splitting)

['captain@', 'jack', 'sparrow', '?is', 'the', 'greatest!', 'of', 'all', 'pirates?', 'git', 'status', 'checks', 'to', 'see', 'if', 'the', 'git', 'project', 'is', 'tracked', '', 'git', 'init%', 'initializes', 'an', 'empty#', 'git', 'repository', 'seed', 'is', 'the', 'comp!any', 'in', 'which', 'i', 'am', 'doing', 'my', 'internship$', 'consistency', 'beats?', 'motivation', '?']

In [318]:
len(white_space_splitting)

43

In [319]:
#removing punctuations and stages
raw_text = re.sub(r'@\w+', '', raw_text, flags=re.MULTILINE)
raw_text = re.sub(r'#\w+', '', raw_text, flags=re.MULTILINE)

#removing anything that is not alphabet
raw_text = re.sub(r'[^a-zA-Z\s]', '', raw_text)

#removing any extra white spaces
raw_text = re.sub(r'\s+', ' ', raw_text).strip() 
print(raw_text)

captain jack sparrow is the greatest of all pirates git status checks to see if the git project is tracked git init initializes an empty git repository seed is the company in which i am doing my internship consistency beats motivation

In [320]:
#splitting by other criteriars
white_space_splitting_with_special_xters = re.split(r'--|[@^*&.$%#@!??/]|\s', raw_text)
print(white_space_splitting_with_special_xters)

['captain', 'jack', 'sparrow', 'is', 'the', 'greatest', 'of', 'all', 'pirates', 'git', 'status', 'checks', 'to', 'see', 'if', 'the', 'git', 'project', 'is', 'tracked', 'git', 'init', 'initializes', 'an', 'empty', 'git', 'repository', 'seed', 'is', 'the', 'company', 'in', 'which', 'i', 'am', 'doing', 'my', 'internship', 'consistency', 'beats', 'motivation']

In [321]:
#removes whitespaces from the text 
strip_text = [word.strip() for word in white_space_splitting_with_special_xters if word.strip()]
len(strip_text)

41

In [322]:
print(strip_text)

['captain', 'jack', 'sparrow', 'is', 'the', 'greatest', 'of', 'all', 'pirates', 'git', 'status', 'checks', 'to', 'see', 'if', 'the', 'git', 'project', 'is', 'tracked', 'git', 'init', 'initializes', 'an', 'empty', 'git', 'repository', 'seed', 'is', 'the', 'company', 'in', 'which', 'i', 'am', 'doing', 'my', 'internship', 'consistency', 'beats', 'motivation']

In [323]:
#removing duplicates and in alphabetical order
sorted_strip_text = sorted(set(strip_text))
print(sorted_strip_text)
len(sorted_strip_text)

['all', 'am', 'an', 'beats', 'captain', 'checks', 'company', 'consistency', 'doing', 'empty', 'git', 'greatest', 'i', 'if', 'in', 'init', 'initializes', 'internship', 'is', 'jack', 'motivation', 'my', 'of', 'pirates', 'project', 'repository', 'see', 'seed', 'sparrow', 'status', 'the', 'to', 'tracked', 'which']

34

In [324]:
#enumerate keeps track of idex and words by pairing the index to the word 
for idx,token in enumerate(sorted_strip_text):
    print(f'( {idx}, {token})')

( 0, all)
( 1, am)
( 2, an)
( 3, beats)
( 4, captain)
( 5, checks)
( 6, company)
( 7, consistency)
( 8, doing)
( 9, empty)
( 10, git)
( 11, greatest)
( 12, i)
( 13, if)
( 14, in)
( 15, init)
( 16, initializes)
( 17, internship)
( 18, is)
( 19, jack)
( 20, motivation)
( 21, my)
( 22, of)
( 23, pirates)
( 24, project)
( 25, repository)
( 26, see)
( 27, seed)
( 28, sparrow)
( 29, status)
( 30, the)
( 31, to)
( 32, tracked)
( 33, which)

In [325]:
#assigning the index to the words or tokens 
vocabulary = {}
for idx,token in enumerate(sorted_strip_text):
    vocabulary [token] = idx
vocabulary

{'all': 0,
 'am': 1,
 'an': 2,
 'beats': 3,
 'captain': 4,
 'checks': 5,
 'company': 6,
 'consistency': 7,
 'doing': 8,
 'empty': 9,
 'git': 10,
 'greatest': 11,
 'i': 12,
 'if': 13,
 'in': 14,
 'init': 15,
 'initializes': 16,
 'internship': 17,
 'is': 18,
 'jack': 19,
 'motivation': 20,
 'my': 21,
 'of': 22,
 'pirates': 23,
 'project': 24,
 'repository': 25,
 'see': 26,
 'seed': 27,
 'sparrow': 28,
 'status': 29,
 'the': 30,
 'to': 31,
 'tracked': 32,
 'which': 33}

In [326]:
id_to_str = {}
for idx,token in enumerate(vocabulary):
    # print(f' ( {idx} , {token})')
    id_to_str[idx] = token
id_to_str

{0: 'all',
 1: 'am',
 2: 'an',
 3: 'beats',
 4: 'captain',
 5: 'checks',
 6: 'company',
 7: 'consistency',
 8: 'doing',
 9: 'empty',
 10: 'git',
 11: 'greatest',
 12: 'i',
 13: 'if',
 14: 'in',
 15: 'init',
 16: 'initializes',
 17: 'internship',
 18: 'is',
 19: 'jack',
 20: 'motivation',
 21: 'my',
 22: 'of',
 23: 'pirates',
 24: 'project',
 25: 'repository',
 26: 'see',
 27: 'seed',
 28: 'sparrow',
 29: 'status',
 30: 'the',
 31: 'to',
 32: 'tracked',
 33: 'which'}

In [327]:
#getting our tokenized text 
token_ids = [vocabulary[word] for word in strip_text]
print(token_ids)

[4, 19, 28, 18, 30, 11, 22, 0, 23, 10, 29, 5, 31, 26, 13, 30, 10, 24, 18, 32, 10, 15, 16, 2, 9, 10, 25, 27, 18, 30, 6, 14, 33, 12, 1, 8, 21, 17, 7, 3, 20]

In [328]:
# recovering our tokenized text to its original state
tokens_recover = [id_to_str[idx] for idx in token_ids]
' '.join(tokens_recover) #.join converts a list to s string and .split converts a string to a list

'captain jack sparrow is the greatest of all pirates git status checks to see if the git project is tracked git init initializes an empty git repository seed is the company in which i am doing my internship consistency beats motivation'

In [ ]:
class tokenizer:
    def __int__(self,vocabulary):
        self.vocabulary = vocabulary